# First Window
<FirstWindow>:
    name: "first"
    
    MDBoxLayout:
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        size_hint: .9, None
        ClickableTextFieldRightIcon


<ClickableTextFieldRightIcon>:
    tts_content: tts_content
    MDTextField:
        id: tts_content
        multiline: True
        mode: 'rectangle'
        hint_text: '  Content  '
    MDIconButton:
        icon: 'play'
        pos_hint: {'right': 1}
        on_release:
            root.speak()
        
